version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: order_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orders"]
      interval: 2s
      timeout: 2s
      retries: 10

  redis:
    image: redis:7
    container_name: order_redis
    ports:
      - "6380:6379"

volumes:
  postgres_data:
